# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117fe6e63d861b5861d298b8340e404dfb438ff95a49ef09b5a9dd45775e847a57543864d9f6c93e39ec6fee5110cc031d8d3ef773e176825845497f8fe6d7fe

test:
  secret_key_base: 9c50c2f18562adafd67acd347feb3e3818355c96a9107e26b8794325278186afc96f7379c07bcc70c42d5f875f3a4c20c4ae0d2e21fd71bed25a839c1c2cc2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
